"""Decision policy (spec section 5.3 / 8.3). STUB: proposes a fixed, small
action sequence per case rather than real EV = Δp_pay × ₹amount − cost −
annoyance decisioning. The real version lands once the Tier 1 uplift
learners are transferred to the domain simulator (spec section 7.3) — this
stub exists so the end-to-end loop is real and runnable before that
transfer happens, per the project's rule 2 (the agent loop must work at
every commit, even with stub components inside it).
"""

from __future__ import annotations

from dataclasses import dataclass

from pydantic import BaseModel

from recovery_ledger.diagnoser.diagnoser import Diagnosis
from recovery_ledger.events.actions import ActionType
from recovery_ledger.events.schemas import (
    Channel,
    FailedPaymentCase,
    FailedSubscriptionCase,
    RecoveryCase,
)
from recovery_ledger.policy.features import case_to_features
from recovery_ledger.policy.uplift.learners import UpliftModel


class ActionDecision(BaseModel):
    action_type: ActionType
    channel: Channel | None
    rationale: str


class DecisionPolicy:
    """Fixed sequence: nudge once on the customer's preferred channel (SMS if
    unset), then a silent retry, then stop. Every real EV/budget/stopping
    constraint still runs downstream (the kernel and the loop's own stopping
    rules) — this only decides which action gets *proposed*."""

    max_attempts: int = 2

    def decide(self, case: RecoveryCase, diagnosis: Diagnosis, attempts_so_far: int) -> ActionDecision:
        if attempts_so_far >= self.max_attempts:
            return ActionDecision(
                action_type=ActionType.STOP, channel=None,
                rationale=f"stub policy: reached max_attempts={self.max_attempts}",
            )
        if attempts_so_far == 0:
            channel = case.customer.channel_pref or Channel.SMS
            return ActionDecision(
                action_type=ActionType.NUDGE, channel=channel,
                rationale=f"stub policy: first contact via {channel.value} ({diagnosis.taxonomy})",
            )
        return ActionDecision(
            action_type=ActionType.RETRY, channel=None,
            rationale="stub policy: second attempt, silent retry",
        )


CHANNEL_COST = {
    Channel.EMAIL: 0.1,
    Channel.WHATSAPP: 0.3,
    Channel.SMS: 0.5,
    Channel.VOICE: 5.0,
    Channel.RETRY: 0.0,
}

# Retry economics are treated as known operational statistics (spec section
# 3.2 cites these as published industry figures — "automated retries recover
# 15-20% of failed transactions", "subscription smart-retry recovers up to
# 57%") — unlike customer-level response to CONTACT, which is exactly the
# heterogeneous, unobservable-without-inference quantity the uplift model
# exists to learn (spec's N1/N2 novelty claims). These numbers are the same
# ones sim/environment.py uses internally, by design: this represents "what
# a real system would plausibly know" about retry success rates from
# historical data, not a leak of the simulator's hidden state.
RETRY_SUCCESS_PROB_SUBSCRIPTION = 0.35
RETRY_SUCCESS_PROB_HARD_DECLINE = 0.01
RETRY_SUCCESS_PROB_GENERIC = 0.17


def _retry_success_prob(case: RecoveryCase) -> float:
    if isinstance(case, FailedSubscriptionCase):
        return RETRY_SUCCESS_PROB_SUBSCRIPTION
    if isinstance(case, FailedPaymentCase) and case.is_hard_decline:
        return RETRY_SUCCESS_PROB_HARD_DECLINE
    return RETRY_SUCCESS_PROB_GENERIC


@dataclass
class EVDecisionPolicy:
    """EV(action | state) = delta_p_pay(action) x amount_at_risk
                            - channel_cost(action)
                            - lambda_annoyance x annoyance_cost(action, history)
       (spec section 8.3). Simplified from the full spec formula: no
       explicit lambda_churn x P(churn) x LTV term — modelling per-customer
       LTV would need assumptions this project has no basis to validate, so
       it's left out rather than invented. annoyance_cost is approximated
       as proportional to attempt count, since the policy cannot observe
       the simulator's true hidden annoyance state (nor could a real
       system observe a customer's true annoyance) — only that repeated
       contact carries rising expected cost.

    `uplift_model` must already be fitted (see
    experiments/tier2_simulation/run_batch.py for how it's trained: a
    T-learner from policy/uplift/learners.py — the same class validated in
    Tier 1 — fit on randomised-contact data generated by
    sim/environment.py)."""

    uplift_model: UpliftModel
    lambda_annoyance: float = 30.0
    max_attempts: int = 3

    def decide(self, case: RecoveryCase, diagnosis: Diagnosis, attempts_so_far: int) -> ActionDecision:
        if attempts_so_far >= self.max_attempts:
            return ActionDecision(
                action_type=ActionType.STOP, channel=None,
                rationale=f"EV policy: reached max_attempts={self.max_attempts}",
            )

        features = case_to_features(case).reshape(1, -1)
        tau_hat = float(self.uplift_model.predict_cate(features)[0])

        channel = case.customer.channel_pref or Channel.SMS
        ev_nudge = (
            tau_hat * case.amount_at_risk
            - CHANNEL_COST[channel]
            - self.lambda_annoyance * attempts_so_far
        )

        retry_applicable = isinstance(case, (FailedPaymentCase, FailedSubscriptionCase))
        ev_retry = _retry_success_prob(case) * case.amount_at_risk if retry_applicable else float("-inf")

        ev_wait = 0.0  # the reference point every other action must beat

        best_action, best_ev = max(
            [(ActionType.NUDGE, ev_nudge), (ActionType.RETRY, ev_retry), (ActionType.WAIT, ev_wait)],
            key=lambda pair: pair[1],
        )

        if best_ev <= 0:
            return ActionDecision(
                action_type=ActionType.STOP, channel=None,
                rationale=f"EV policy: best action {best_action.value} has EV={best_ev:.2f} <= 0",
            )
        if best_action == ActionType.NUDGE:
            return ActionDecision(
                action_type=ActionType.NUDGE, channel=channel,
                rationale=f"EV policy: tau_hat={tau_hat:.4f}, EV={best_ev:.2f}",
            )
        return ActionDecision(
            action_type=ActionType.RETRY, channel=None,
            rationale=f"EV policy: retry EV={best_ev:.2f} (p_success={_retry_success_prob(case):.2f})",
        )


@dataclass
class DoNothingPolicy:
    """The randomised no-contact holdout arm (spec section 11.1) — always
    proposes WAIT, for the same number of attempt-windows a contact policy
    would have used, then stops. This is what makes an "incremental"
    recovery number meaningful rather than an artifact of comparing
    different-length observation periods: it's the counterfactual every
    other policy is measured against, over the same horizon."""

    max_attempts: int = 3

    def decide(self, case: RecoveryCase, diagnosis: Diagnosis, attempts_so_far: int) -> ActionDecision:
        if attempts_so_far >= self.max_attempts:
            return ActionDecision(
                action_type=ActionType.STOP, channel=None,
                rationale=f"holdout: reached max_attempts={self.max_attempts}",
            )
        return ActionDecision(
            action_type=ActionType.WAIT, channel=None,
            rationale="holdout: no-contact baseline",
        )


@dataclass
class BlastEveryonePolicy:
    """Contact every case, every attempt, no discrimination between
    persuadables and do-not-disturbs — the naive "when in doubt, reach out"
    policy this project's whole thesis is that you can beat (spec section
    11.3, baseline 2)."""

    max_attempts: int = 3
    default_channel: Channel = Channel.SMS

    def decide(self, case: RecoveryCase, diagnosis: Diagnosis, attempts_so_far: int) -> ActionDecision:
        if attempts_so_far >= self.max_attempts:
            return ActionDecision(
                action_type=ActionType.STOP, channel=None,
                rationale=f"blast-everyone: reached max_attempts={self.max_attempts}",
            )
        channel = case.customer.channel_pref or self.default_channel
        return ActionDecision(
            action_type=ActionType.NUDGE, channel=channel,
            rationale="blast-everyone: always contact, no targeting",
        )


class RazorpayCurrentPolicy:
    """A single automated retry, then hand the case back to the merchant
    (spec section 3.3): "Razorpay Subscriptions currently retries a failed
    recurring charge once... then moves the subscription to halted."
    Modelled as: one silent RETRY, then STOP — everything after that first
    retry is, by design, unowned by this policy (spec section 11.3,
    baseline 3)."""

    def decide(self, case: RecoveryCase, diagnosis: Diagnosis, attempts_so_far: int) -> ActionDecision:
        if attempts_so_far == 0:
            return ActionDecision(
                action_type=ActionType.RETRY, channel=None,
                rationale="razorpay-current: single automated retry",
            )
        return ActionDecision(
            action_type=ActionType.STOP, channel=None,
            rationale="razorpay-current: halted after first retry, handed back to merchant",
        )


@dataclass
class RulesBasedDunningPolicy:
    """The industry-standard fixed cadence — a 3-contact ladder regardless
    of any signal about who's actually persuadable (spec section 11.3,
    baseline 4: "fixed 3-email ladder — the industry standard")."""

    max_attempts: int = 3
    default_channel: Channel = Channel.EMAIL

    def decide(self, case: RecoveryCase, diagnosis: Diagnosis, attempts_so_far: int) -> ActionDecision:
        if attempts_so_far >= self.max_attempts:
            return ActionDecision(
                action_type=ActionType.STOP, channel=None,
                rationale="rules-based dunning: fixed 3-contact ladder complete",
            )
        channel = case.customer.channel_pref or self.default_channel
        return ActionDecision(
            action_type=ActionType.NUDGE, channel=channel,
            rationale=f"rules-based dunning: fixed contact {attempts_so_far + 1}/{self.max_attempts}",
        )
