"""Decision policy (spec section 5.3 / 8.3). STUB: proposes a fixed, small
action sequence per case rather than real EV = Δp_pay × ₹amount − cost −
annoyance decisioning. The real version lands once the Tier 1 uplift
learners are transferred to the domain simulator (spec section 7.3) — this
stub exists so the end-to-end loop is real and runnable before that
transfer happens, per the project's rule 2 (the agent loop must work at
every commit, even with stub components inside it).
"""

from __future__ import annotations

import hashlib
from dataclasses import dataclass

from pydantic import BaseModel

from recovery_ledger.diagnoser.diagnoser import Diagnosis
from recovery_ledger.events.actions import ActionType
from recovery_ledger.events.schemas import (
    Channel,
    FailedPaymentCase,
    FailedSubscriptionCase,
    RecoveryCase,
)
from recovery_ledger.policy.features import case_to_features
from recovery_ledger.policy.uplift.learners import UpliftModel


class ActionDecision(BaseModel):
    action_type: ActionType
    channel: Channel | None
    rationale: str


class DecisionPolicy:
    """Fixed sequence: nudge once on the customer's preferred channel (SMS if
    unset), then a silent retry, then stop. Every real EV/budget/stopping
    constraint still runs downstream (the kernel and the loop's own stopping
    rules) — this only decides which action gets *proposed*."""

    max_attempts: int = 2

    def decide(self, case: RecoveryCase, diagnosis: Diagnosis, attempts_so_far: int) -> ActionDecision:
        if attempts_so_far >= self.max_attempts:
            return ActionDecision(
                action_type=ActionType.STOP, channel=None,
                rationale=f"stub policy: reached max_attempts={self.max_attempts}",
            )
        if attempts_so_far == 0:
            channel = case.customer.channel_pref or Channel.SMS
            return ActionDecision(
                action_type=ActionType.NUDGE, channel=channel,
                rationale=f"stub policy: first contact via {channel.value} ({diagnosis.taxonomy})",
            )
        return ActionDecision(
            action_type=ActionType.RETRY, channel=None,
            rationale="stub policy: second attempt, silent retry",
        )


CHANNEL_COST = {
    Channel.EMAIL: 0.1,
    Channel.WHATSAPP: 0.3,
    Channel.SMS: 0.5,
    Channel.VOICE: 5.0,
    Channel.RETRY: 0.0,
}

# Retry economics are treated as known operational statistics (spec section
# 3.2 cites these as published industry figures — "automated retries recover
# 15-20% of failed transactions", "subscription smart-retry recovers up to
# 57%") — unlike customer-level response to CONTACT, which is exactly the
# heterogeneous, unobservable-without-inference quantity the uplift model
# exists to learn (spec's N1/N2 novelty claims). These numbers are the same
# ones sim/environment.py uses internally, by design: this represents "what
# a real system would plausibly know" about retry success rates from
# historical data, not a leak of the simulator's hidden state.
RETRY_SUCCESS_PROB_SUBSCRIPTION = 0.35
RETRY_SUCCESS_PROB_HARD_DECLINE = 0.01
RETRY_SUCCESS_PROB_GENERIC = 0.17


def _retry_success_prob(case: RecoveryCase) -> float:
    if isinstance(case, FailedSubscriptionCase):
        return RETRY_SUCCESS_PROB_SUBSCRIPTION
    if isinstance(case, FailedPaymentCase) and case.is_hard_decline:
        return RETRY_SUCCESS_PROB_HARD_DECLINE
    return RETRY_SUCCESS_PROB_GENERIC


@dataclass
class EVDecisionPolicy:
    """EV(action | state) = delta_p_pay(action) x amount_at_risk
                            - channel_cost(action)
                            - lambda_annoyance x annoyance_cost(action, history)
       (spec section 8.3). Simplified from the full spec formula: no
       explicit lambda_churn x P(churn) x LTV term — modelling per-customer
       LTV would need assumptions this project has no basis to validate, so
       it's left out rather than invented. annoyance_cost is approximated
       as proportional to attempt count, since the policy cannot observe
       the simulator's true hidden annoyance state (nor could a real
       system observe a customer's true annoyance) — only that repeated
       contact carries rising expected cost.

    `uplift_model` must already be fitted (see
    experiments/tier2_simulation/run_batch.py for how it's trained: a
    T-learner from policy/uplift/learners.py — the same class validated in
    Tier 1 — fit on randomised-contact data generated by
    sim/environment.py)."""

    uplift_model: UpliftModel
    lambda_annoyance: float = 30.0
    max_attempts: int = 3

    def decide(self, case: RecoveryCase, diagnosis: Diagnosis, attempts_so_far: int) -> ActionDecision:
        if attempts_so_far >= self.max_attempts:
            return ActionDecision(
                action_type=ActionType.STOP, channel=None,
                rationale=f"EV policy: reached max_attempts={self.max_attempts}",
            )

        features = case_to_features(case).reshape(1, -1)
        tau_hat = float(self.uplift_model.predict_cate(features)[0])

        channel = case.customer.channel_pref or Channel.SMS
        ev_nudge = (
            tau_hat * case.amount_at_risk
            - CHANNEL_COST[channel]
            - self.lambda_annoyance * attempts_so_far
        )

        retry_applicable = isinstance(case, (FailedPaymentCase, FailedSubscriptionCase))
        ev_retry = _retry_success_prob(case) * case.amount_at_risk if retry_applicable else float("-inf")

        ev_wait = 0.0  # the reference point every other action must beat

        best_action, best_ev = max(
            [(ActionType.NUDGE, ev_nudge), (ActionType.RETRY, ev_retry), (ActionType.WAIT, ev_wait)],
            key=lambda pair: pair[1],
        )

        if best_ev <= 0:
            # WAIT, not STOP. These are NOT equivalent, and conflating them
            # was a real bug (found 2026-08-24): STOP abandons the case and
            # forfeits the organic self-resolution the customer might have
            # reached anyway, while WAIT costs nothing, contacts nobody, and
            # keeps the case eligible for that free recovery. Before this
            # fix the EV policy recovered only 8.1% of overdue receivables
            # against the do-nothing baseline's 13.9% — i.e. it was doing
            # actively WORSE than not having an agent at all on that segment,
            # purely by giving up on cases too eagerly.
            #
            # Terminating on genuinely exhausted budget is still correct and
            # still happens, via max_attempts above.
            return ActionDecision(
                action_type=ActionType.WAIT, channel=None,
                rationale=(
                    f"EV policy: no action beats waiting "
                    f"(best was {best_action.value} at EV={best_ev:.2f}); "
                    f"waiting is free and preserves organic recovery"
                ),
            )
        if best_action == ActionType.NUDGE:
            return ActionDecision(
                action_type=ActionType.NUDGE, channel=channel,
                rationale=f"EV policy: tau_hat={tau_hat:.4f}, EV={best_ev:.2f}",
            )
        return ActionDecision(
            action_type=ActionType.RETRY, channel=None,
            rationale=f"EV policy: retry EV={best_ev:.2f} (p_success={_retry_success_prob(case):.2f})",
        )


@dataclass
class DoNothingPolicy:
    """The randomised no-contact holdout arm (spec section 11.1) — always
    proposes WAIT, for the same number of attempt-windows a contact policy
    would have used, then stops. This is what makes an "incremental"
    recovery number meaningful rather than an artifact of comparing
    different-length observation periods: it's the counterfactual every
    other policy is measured against, over the same horizon."""

    max_attempts: int = 3

    def decide(self, case: RecoveryCase, diagnosis: Diagnosis, attempts_so_far: int) -> ActionDecision:
        if attempts_so_far >= self.max_attempts:
            return ActionDecision(
                action_type=ActionType.STOP, channel=None,
                rationale=f"holdout: reached max_attempts={self.max_attempts}",
            )
        return ActionDecision(
            action_type=ActionType.WAIT, channel=None,
            rationale="holdout: no-contact baseline",
        )


@dataclass
class LookaheadEVDecisionPolicy:
    """EV policy that values the WHOLE REMAINING ATTEMPT SEQUENCE rather
    than one greedy step.

    Why this exists: the 5-baseline comparison (2026-08-24) found the
    greedy `EVDecisionPolicy` recovering *less* than blindly contacting
    everyone. Investigation ruled out annoyance-cost miscalibration
    (sweeping `lambda_annoyance` to 0 barely moved recovery) and pointed at
    the greedy formulation itself: `sim/environment.py` treats each contact
    as close to an independent trial, so persistence compounds. A policy
    that asks only "is one more nudge worth it *right now*" gives up on
    cases where the sequence of remaining attempts is collectively
    worthwhile — and does so more often when `tau_hat` is noisy, which it
    is (~0.4 correlation with truth, not 1.0).

    The fix is a small finite-horizon dynamic program over the remaining
    attempt budget, solved by backward induction:

        V(k) = max over admissible actions a of
                   [ immediate_value(a, k) + (1 - p_resolve(a)) * V(k+1) ]
        V(max_attempts) = 0        # horizon: no attempts left

    `immediate_value` is the same incremental-EV expression the greedy
    policy uses (Δp × ₹amount − channel cost − annoyance cost). The
    `(1 - p_resolve)` factor is what the greedy version was missing: an
    action's value includes the option to keep working the case if it
    doesn't resolve now.

    STATED ASSUMPTION: `p_resolve` for a contact is approximated as
    `base_resolution_prob + tau_hat`, since the uplift model estimates the
    *incremental* effect (CATE) and not an absolute payment probability.
    That approximation is the weakest link in this policy and is why
    `base_resolution_prob` is an explicit parameter rather than a hidden
    constant — a real deployment would estimate absolute payment
    probability directly, alongside the CATE.
    """

    uplift_model: UpliftModel
    lambda_annoyance: float = 30.0
    max_attempts: int = 3
    base_resolution_prob: float = 0.05

    def _immediate_and_resolve(
        self, case: RecoveryCase, tau_hat: float, attempt_index: int
    ) -> dict[ActionType, tuple[float, float, Channel | None]]:
        """(immediate incremental value, P(resolve), channel) per action."""
        channel = case.customer.channel_pref or Channel.SMS
        nudge_value = (
            tau_hat * case.amount_at_risk
            - CHANNEL_COST[channel]
            - self.lambda_annoyance * attempt_index
        )
        nudge_resolve = float(min(max(self.base_resolution_prob + tau_hat, 0.0), 0.95))

        options: dict[ActionType, tuple[float, float, Channel | None]] = {
            ActionType.NUDGE: (nudge_value, nudge_resolve, channel),
            ActionType.WAIT: (0.0, self.base_resolution_prob, None),
        }
        if isinstance(case, (FailedPaymentCase, FailedSubscriptionCase)):
            p_retry = _retry_success_prob(case)
            options[ActionType.RETRY] = (p_retry * case.amount_at_risk, p_retry, None)
        return options

    def _solve(self, case: RecoveryCase, tau_hat: float, attempts_so_far: int):
        """Backward induction from the horizon back to the current attempt.
        Returns (best_action, channel, value_of_acting_now)."""
        future_value = 0.0
        best_at_current: tuple[ActionType, Channel | None, float] | None = None

        for k in range(self.max_attempts - 1, attempts_so_far - 1, -1):
            options = self._immediate_and_resolve(case, tau_hat, k)
            best_action, best_channel, best_value = ActionType.STOP, None, 0.0
            for action, (immediate, p_resolve, channel) in options.items():
                total = immediate + (1.0 - p_resolve) * future_value
                if total > best_value:
                    best_action, best_channel, best_value = action, channel, total
            future_value = best_value
            if k == attempts_so_far:
                best_at_current = (best_action, best_channel, best_value)

        assert best_at_current is not None
        return best_at_current

    def decide(self, case: RecoveryCase, diagnosis: Diagnosis, attempts_so_far: int) -> ActionDecision:
        if attempts_so_far >= self.max_attempts:
            return ActionDecision(
                action_type=ActionType.STOP, channel=None,
                rationale=f"lookahead EV: reached max_attempts={self.max_attempts}",
            )

        features = case_to_features(case).reshape(1, -1)
        tau_hat = float(self.uplift_model.predict_cate(features)[0])
        action, channel, value = self._solve(case, tau_hat, attempts_so_far)

        if action == ActionType.STOP or value <= 0:
            # WAIT rather than STOP, for the same reason as EVDecisionPolicy —
            # waiting is free and preserves organic recovery, abandoning the
            # case throws it away.
            return ActionDecision(
                action_type=ActionType.WAIT, channel=None,
                rationale=(
                    f"lookahead EV: no remaining action sequence beats waiting "
                    f"(tau_hat={tau_hat:.4f}); waiting is free"
                ),
            )
        return ActionDecision(
            action_type=action, channel=channel,
            rationale=f"lookahead EV: tau_hat={tau_hat:.4f}, sequence value={value:.2f}",
        )


@dataclass
class RandomTargetingPolicy:
    """Contacts a RANDOM subset of cases, at a chosen rate, ignoring every
    signal. This is the control that makes the efficiency claim falsifiable.

    "Our policy gets the same recovery as mass-contact with 61% fewer
    contacts" is only evidence of good *targeting* if a policy that contacts
    the same reduced number of cases AT RANDOM does measurably worse. If
    random targeting at matched volume performs just as well, then the
    result says something about diminishing returns to contact volume and
    nothing whatsoever about the uplift model — a distinction worth being
    able to prove rather than assert (added 2026-08-24).

    Seeded per case id so the choice is deterministic and reproducible.
    """

    contact_rate: float = 0.5
    max_attempts: int = 3
    seed: int = 0
    default_channel: Channel = Channel.SMS

    def _contacts_this_case(self, case: RecoveryCase) -> bool:
        digest = hashlib.sha256(f"{self.seed}:{case.case_id}".encode()).digest()
        draw = int.from_bytes(digest[:8], "big") / 2**64
        return draw < self.contact_rate

    def decide(self, case: RecoveryCase, diagnosis: Diagnosis, attempts_so_far: int) -> ActionDecision:
        if attempts_so_far >= self.max_attempts:
            return ActionDecision(
                action_type=ActionType.STOP, channel=None,
                rationale=f"random targeting: reached max_attempts={self.max_attempts}",
            )
        if not self._contacts_this_case(case):
            return ActionDecision(
                action_type=ActionType.WAIT, channel=None,
                rationale=f"random targeting: case not selected (rate={self.contact_rate})",
            )
        channel = case.customer.channel_pref or self.default_channel
        return ActionDecision(
            action_type=ActionType.NUDGE, channel=channel,
            rationale=f"random targeting: case selected at random (rate={self.contact_rate})",
        )


@dataclass
class BlastEveryonePolicy:
    """Contact every case, every attempt, no discrimination between
    persuadables and do-not-disturbs — the naive "when in doubt, reach out"
    policy this project's whole thesis is that you can beat (spec section
    11.3, baseline 2)."""

    max_attempts: int = 3
    default_channel: Channel = Channel.SMS

    def decide(self, case: RecoveryCase, diagnosis: Diagnosis, attempts_so_far: int) -> ActionDecision:
        if attempts_so_far >= self.max_attempts:
            return ActionDecision(
                action_type=ActionType.STOP, channel=None,
                rationale=f"blast-everyone: reached max_attempts={self.max_attempts}",
            )
        channel = case.customer.channel_pref or self.default_channel
        return ActionDecision(
            action_type=ActionType.NUDGE, channel=channel,
            rationale="blast-everyone: always contact, no targeting",
        )


class RazorpayCurrentPolicy:
    """A single automated retry, then hand the case back to the merchant
    (spec section 3.3): "Razorpay Subscriptions currently retries a failed
    recurring charge once... then moves the subscription to halted."
    Modelled as: one silent RETRY, then STOP — everything after that first
    retry is, by design, unowned by this policy (spec section 11.3,
    baseline 3)."""

    def decide(self, case: RecoveryCase, diagnosis: Diagnosis, attempts_so_far: int) -> ActionDecision:
        if attempts_so_far == 0:
            return ActionDecision(
                action_type=ActionType.RETRY, channel=None,
                rationale="razorpay-current: single automated retry",
            )
        return ActionDecision(
            action_type=ActionType.STOP, channel=None,
            rationale="razorpay-current: halted after first retry, handed back to merchant",
        )


@dataclass
class RulesBasedDunningPolicy:
    """The industry-standard fixed cadence — a 3-contact ladder regardless
    of any signal about who's actually persuadable (spec section 11.3,
    baseline 4: "fixed 3-email ladder — the industry standard")."""

    max_attempts: int = 3
    default_channel: Channel = Channel.EMAIL

    def decide(self, case: RecoveryCase, diagnosis: Diagnosis, attempts_so_far: int) -> ActionDecision:
        if attempts_so_far >= self.max_attempts:
            return ActionDecision(
                action_type=ActionType.STOP, channel=None,
                rationale="rules-based dunning: fixed 3-contact ladder complete",
            )
        channel = case.customer.channel_pref or self.default_channel
        return ActionDecision(
            action_type=ActionType.NUDGE, channel=channel,
            rationale=f"rules-based dunning: fixed contact {attempts_so_far + 1}/{self.max_attempts}",
        )
